name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.4
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: |
          poetry run python -m unittest discover -s github_standards/test -p '*.py'

  sonatype-lifecycle:
    name: Sonatype Lifecycle Policy Evaluation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sonatype Lifecycle Evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
          username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
          password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
          application-id: github-management
          stage: ${{ github.ref == 'refs/heads/main' && 'build' || 'develop' }}
          scan-targets: '.'
